import { CustomsDutyRule, Employee, Hub, RoutePricing, ThemeMode, User } from '../types';

export const THEMES: { id: ThemeMode; labelAr: string; labelEn: string; bgClass: string; cardClass: string; accentColor: string }[] = [
  { id: 'slate', labelAr: 'الوضع الداكن الفاخر', labelEn: 'Luxury Slate Dark', bgClass: 'bg-slate-900 text-slate-100', cardClass: 'bg-slate-800 border-slate-700 text-slate-100', accentColor: '#FF6B00' },
  { id: 'light', labelAr: 'الوضع الأبيض المؤسسي', labelEn: 'Enterprise Clean Light', bgClass: 'bg-slate-100 text-slate-900', cardClass: 'bg-white border-slate-300 text-slate-900', accentColor: '#FF6B00' },
  { id: 'navy', labelAr: 'الأزرق البحري الجوي', labelEn: 'Aerospace Deep Navy', bgClass: 'bg-slate-950 text-sky-100', cardClass: 'bg-slate-900/90 border-sky-900/50 text-sky-100', accentColor: '#FF6B00' },
  { id: 'emerald', labelAr: 'الزمردي العربي', labelEn: 'Arabian Emerald', bgClass: 'bg-stone-950 text-emerald-100', cardClass: 'bg-stone-900 border-emerald-900/60 text-emerald-100', accentColor: '#FF6B00' },
  { id: 'desert', labelAr: 'الصحراء والذهب', labelEn: 'Desert Gold Warm', bgClass: 'bg-amber-950 text-amber-100', cardClass: 'bg-amber-950/80 border-amber-800/50 text-amber-100', accentColor: '#FF6B00' },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-amm-101',
    staffCode: 'EMP-AMM-101',
    fullName: 'عمر النجار (Omar Al-Najjar)',
    email: 'agent.amman@thouesa.com',
    phone: '+962 78 888 9911',
    assignedHubId: 'hub-amm',
    assignedHubName: 'مركز عمان الرئيسي (AMM-01)',
    role: 'HUB_AGENT',
    passwordPin: '1234',
    isActive: true,
    permissions: ['INTAKE_INSPECT', 'MANIFEST_BUILD', 'HANDOVER_DISPATCH', 'RECIPIENT_DELIVERY'],
    createdAt: '2025-08-01T09:00:00Z',
  },
  {
    id: 'emp-alg-201',
    staffCode: 'EMP-ALG-201',
    fullName: 'سفيان مرابط (Sofiane Merabet)',
    email: 'manager.algiers@thouesa.com',
    phone: '+213 21 73 00 22',
    assignedHubId: 'hub-alg',
    assignedHubName: 'مركز الجزائر الدولي (ALG-01)',
    role: 'HUB_MANAGER',
    passwordPin: '1234',
    isActive: true,
    permissions: ['INTAKE_INSPECT', 'MANIFEST_BUILD', 'HANDOVER_DISPATCH', 'DESTINATION_INTAKE', 'RECIPIENT_DELIVERY', 'DISPUTE_ESCALATION'],
    createdAt: '2025-05-10T12:00:00Z',
  },
  {
    id: 'emp-mct-102',
    staffCode: 'EMP-MCT-102',
    fullName: 'سالم البلوشي (Salim Al-Balushi)',
    email: 'agent.muscat@thouesa.com',
    phone: '+968 9123 4567',
    assignedHubId: 'hub-mct',
    assignedHubName: 'مركز مسقط اللوجستي (MCT-01)',
    role: 'HUB_AGENT',
    passwordPin: '1234',
    isActive: true,
    permissions: ['INTAKE_INSPECT', 'MANIFEST_BUILD', 'HANDOVER_DISPATCH', 'RECIPIENT_DELIVERY'],
    createdAt: '2025-07-12T10:00:00Z',
  },
  {
    id: 'emp-cai-301',
    staffCode: 'EMP-CAI-301',
    fullName: 'محمود الشريف (Mahmoud El-Sherif)',
    email: 'agent.cairo@thouesa.com',
    phone: '+20 2 2400 1199',
    assignedHubId: 'hub-cai',
    assignedHubName: 'مركز القاهرة المركزي (CAI-01)',
    role: 'HUB_AGENT',
    passwordPin: '1234',
    isActive: true,
    permissions: ['INTAKE_INSPECT', 'MANIFEST_BUILD', 'DESTINATION_INTAKE', 'RECIPIENT_DELIVERY'],
    createdAt: '2025-09-15T11:00:00Z',
  },
  {
    id: 'emp-ruh-401',
    staffCode: 'EMP-RUH-401',
    fullName: 'فهد العتيبي (Fahad Al-Otaibi)',
    email: 'manager.riyadh@thouesa.com',
    phone: '+966 11 490 8822',
    assignedHubId: 'hub-ruh',
    assignedHubName: 'مركز الرياض النموذجي (RUH-01)',
    role: 'HUB_MANAGER',
    passwordPin: '1234',
    isActive: true,
    permissions: ['INTAKE_INSPECT', 'MANIFEST_BUILD', 'HANDOVER_DISPATCH', 'DESTINATION_INTAKE', 'RECIPIENT_DELIVERY'],
    createdAt: '2025-10-01T08:00:00Z',
  },
];

export const HUBS_DATA: Hub[] = [
  {
    id: 'hub-amm',
    code: 'AMM-01',
    nameAr: 'مركز عمان الرئيسي (الأردن)',
    nameEn: 'Amman Main Hub (Jordan)',
    countryCode: 'JOR',
    countryNameAr: 'الأردن',
    countryNameEn: 'Jordan',
    cityAr: 'عمان',
    cityEn: 'Amman',
    address: 'شارع مكة، مجمع الأعمال، الطابق الأرضي، عمان',
    phone: '+962 6 550 4400',
    storageCapacityKg: 1200,
    currentUsedKg: 420,
    isActive: true,
    managerName: 'أحمد المجالي',
    operatingHours: '08:00 - 22:00 Daily',
  },
  {
    id: 'hub-alg',
    code: 'ALG-01',
    nameAr: 'مركز الجزائر الدولي (الجزائر)',
    nameEn: 'Algiers International Hub (Algeria)',
    countryCode: 'DZA',
    countryNameAr: 'الجزائر',
    countryNameEn: 'Algeria',
    cityAr: 'الجزائر العاصمة',
    cityEn: 'Algiers',
    address: 'شارع ديدوش مراد، مبنى النقل اللوجستي، الجزائر',
    phone: '+213 21 73 00 22',
    storageCapacityKg: 1500,
    currentUsedKg: 680,
    isActive: true,
    managerName: 'سفيان مرابط',
    operatingHours: '08:30 - 21:00 Daily',
  },
  {
    id: 'hub-mct',
    code: 'MCT-01',
    nameAr: 'مركز مسقط اللوجستي (سلطنة عُمان)',
    nameEn: 'Muscat Logistics Hub (Oman)',
    countryCode: 'OMN',
    countryNameAr: 'سلطنة عُمان',
    countryNameEn: 'Oman',
    cityAr: 'مسقط',
    cityEn: 'Muscat',
    address: 'مرتفعات المطار، المنطقة الحرة للشحن الجوي، مسقط',
    phone: '+968 24 110 990',
    storageCapacityKg: 1800,
    currentUsedKg: 350,
    isActive: true,
    managerName: 'سالم البلوشي',
    operatingHours: '08:00 - 22:00 Daily',
  },
  {
    id: 'hub-cai',
    code: 'CAI-01',
    nameAr: 'مركز القاهرة المركزي (مصر)',
    nameEn: 'Cairo Central Hub (Egypt)',
    countryCode: 'EGY',
    countryNameAr: 'مصر',
    countryNameEn: 'Egypt',
    cityAr: 'القاهرة',
    cityEn: 'Cairo',
    address: 'مدينة نصر، عباس العقاد، مجمع الخدمات اللوجستية، القاهرة',
    phone: '+20 2 2400 1199',
    storageCapacityKg: 2000,
    currentUsedKg: 910,
    isActive: true,
    managerName: 'محمود الشريف',
    operatingHours: '08:00 - 23:00 Daily',
  },
  {
    id: 'hub-ruh',
    code: 'RUH-01',
    nameAr: 'مركز الرياض النموذجي (السعودية)',
    nameEn: 'Riyadh Flagship Hub (Saudi Arabia)',
    countryCode: 'SAU',
    countryNameAr: 'السعودية',
    countryNameEn: 'Saudi Arabia',
    cityAr: 'الرياض',
    cityEn: 'Riyadh',
    address: 'حي السلي، المنطقة اللوجستية المركزية، الرياض',
    phone: '+966 11 490 8822',
    storageCapacityKg: 2500,
    currentUsedKg: 830,
    isActive: true,
    managerName: 'فهد العتيبي',
    operatingHours: '08:00 - 23:00 Daily',
  },
];

export const ROUTE_PRICING: RoutePricing[] = [
  {
    originCountry: 'JOR',
    destinationCountry: 'DZA',
    basePriceKg: 18.0,
    travelerShareKg: 12.0,
    hubFeeKg: 4.5,
    insuranceRatePercent: 2.5,
    averageFlightHours: 5.5,
  },
  {
    originCountry: 'DZA',
    destinationCountry: 'JOR',
    basePriceKg: 18.0,
    travelerShareKg: 12.0,
    hubFeeKg: 4.5,
    insuranceRatePercent: 2.5,
    averageFlightHours: 5.5,
  },
  {
    originCountry: 'JOR',
    destinationCountry: 'EGY',
    basePriceKg: 12.0,
    travelerShareKg: 8.0,
    hubFeeKg: 3.0,
    insuranceRatePercent: 2.0,
    averageFlightHours: 1.5,
  },
  {
    originCountry: 'EGY',
    destinationCountry: 'JOR',
    basePriceKg: 12.0,
    travelerShareKg: 8.0,
    hubFeeKg: 3.0,
    insuranceRatePercent: 2.0,
    averageFlightHours: 1.5,
  },
  {
    originCountry: 'SAU',
    destinationCountry: 'JOR',
    basePriceKg: 14.0,
    travelerShareKg: 9.5,
    hubFeeKg: 3.5,
    insuranceRatePercent: 2.0,
    averageFlightHours: 2.0,
  },
  {
    originCountry: 'JOR',
    destinationCountry: 'SAU',
    basePriceKg: 14.0,
    travelerShareKg: 9.5,
    hubFeeKg: 3.5,
    insuranceRatePercent: 2.0,
    averageFlightHours: 2.0,
  },
  {
    originCountry: 'SAU',
    destinationCountry: 'DZA',
    basePriceKg: 22.0,
    travelerShareKg: 15.0,
    hubFeeKg: 5.0,
    insuranceRatePercent: 2.5,
    averageFlightHours: 6.5,
  },
  {
    originCountry: 'DZA',
    destinationCountry: 'SAU',
    basePriceKg: 22.0,
    travelerShareKg: 15.0,
    hubFeeKg: 5.0,
    insuranceRatePercent: 2.5,
    averageFlightHours: 6.5,
  },
];

export const EXCHANGE_RATES_TO_USD: Record<string, number> = {
  USD: 1.0,
  JOD: 0.709, // 1 USD = 0.709 JOD
  DZA: 134.5, // 1 USD = 134.50 DZD
  DZD: 134.5,
  EGP: 48.85, // 1 USD = 48.85 EGP
  SAR: 3.75, // 1 USD = 3.75 SAR
};

export const DEFAULT_EXCHANGE_RATES = [
  { currency: 'USD' as const, rateToUsd: 1.0, lastUpdated: '2026-08-25T12:00:00Z' },
  { currency: 'JOD' as const, rateToUsd: 0.709, lastUpdated: '2026-08-25T12:00:00Z' },
  { currency: 'DZD' as const, rateToUsd: 134.5, lastUpdated: '2026-08-25T12:00:00Z' },
  { currency: 'EGP' as const, rateToUsd: 48.85, lastUpdated: '2026-08-25T12:00:00Z' },
  { currency: 'SAR' as const, rateToUsd: 3.75, lastUpdated: '2026-08-25T12:00:00Z' },
];

export const DEFAULT_CUSTOMS_RULES: CustomsDutyRule[] = [
  {
    countryCode: 'JOR',
    countryNameAr: 'المملكة الأردنية الهاشمية',
    countryNameEn: 'Jordan',
    standardDutyPercent: 15.0,
    newPersonalGoodsDutyPercent: 12.0,
    commercialNewDutyPercent: 20.0,
    usedPersonalExempt: true,
    minExemptValueUsd: 50.0,
    categoryOverrides: {
      ELECTRONICS: 16.0,
      GIFTS_COSMETICS: 12.0,
      CLOTHING_TEXTILES: 10.0,
      MEDICATIONS_PERMITTED: 5.0,
    },
    notesAr: 'الأمانات الشخصية المستعملة معفاة بالكامل 0%. الأجهزة والإلكترونيات والهدايا الجديدة تخضع لنسبة 12-16%.',
    notesEn: 'Used personal items fully exempt (0%). New boxed electronics & gifts subject to 12-16% duty.',
    lastUpdated: '2026-08-25T12:00:00Z',
    updatedBy: 'System Baseline',
  },
  {
    countryCode: 'DZA',
    countryNameAr: 'الجمهورية الجزائرية الديمقراطية الشعبية',
    countryNameEn: 'Algeria',
    standardDutyPercent: 20.0,
    newPersonalGoodsDutyPercent: 15.0,
    commercialNewDutyPercent: 25.0,
    usedPersonalExempt: true,
    minExemptValueUsd: 60.0,
    categoryOverrides: {
      ELECTRONICS: 18.0,
      GIFTS_COSMETICS: 15.0,
      CLOTHING_TEXTILES: 12.0,
      MEDICATIONS_PERMITTED: 5.0,
    },
    notesAr: 'الأمتعة الشخصية المستعملة معفاة 0%. السلع والهدايا الشخصية الجديدة 15% والبضائع التجارية 25%.',
    notesEn: 'Used luggage exempt 0%. New personal goods/electronics 15%, commercial merchandise 25%.',
    lastUpdated: '2026-08-25T12:00:00Z',
    updatedBy: 'System Baseline',
  },
  {
    countryCode: 'SAU',
    countryNameAr: 'المملكة العربية السعودية',
    countryNameEn: 'Saudi Arabia',
    standardDutyPercent: 15.0,
    newPersonalGoodsDutyPercent: 10.0,
    commercialNewDutyPercent: 15.0,
    usedPersonalExempt: true,
    minExemptValueUsd: 100.0,
    categoryOverrides: {
      ELECTRONICS: 10.0,
      GIFTS_COSMETICS: 15.0,
      CLOTHING_TEXTILES: 10.0,
    },
    notesAr: 'الأمانات الشخصية المستعملة معفاة 0%. السلع الجديدة تخضع لضريبة القيمة المضافة والتعريفة الجمركية 10-15%.',
    notesEn: 'Used effects exempt. New items subject to standard VAT + customs rate (10-15%).',
    lastUpdated: '2026-08-25T12:00:00Z',
    updatedBy: 'System Baseline',
  },
  {
    countryCode: 'EGY',
    countryNameAr: 'جمهورية مصر العربية',
    countryNameEn: 'Egypt',
    standardDutyPercent: 25.0,
    newPersonalGoodsDutyPercent: 15.0,
    commercialNewDutyPercent: 30.0,
    usedPersonalExempt: true,
    minExemptValueUsd: 40.0,
    categoryOverrides: {
      ELECTRONICS: 20.0,
      GIFTS_COSMETICS: 25.0,
      CLOTHING_TEXTILES: 15.0,
    },
    notesAr: 'الأمانات الشخصية المستعملة معفاة 0%. الإلكترونيات والأجهزة الجديدة 20%.',
    notesEn: 'Used luggage 0% exempt. New electronics/cosmetics 20-25%.',
    lastUpdated: '2026-08-25T12:00:00Z',
    updatedBy: 'System Baseline',
  },
  {
    countryCode: 'OMN',
    countryNameAr: 'سلطنة عُمان',
    countryNameEn: 'Oman',
    standardDutyPercent: 10.0,
    newPersonalGoodsDutyPercent: 5.0,
    commercialNewDutyPercent: 12.0,
    usedPersonalExempt: true,
    minExemptValueUsd: 80.0,
    notesAr: 'الأمانات المستعملة معفاة 0%. الأمانات الجديدة 5%.',
    notesEn: 'Used personal items exempt 0%. New goods 5%.',
    lastUpdated: '2026-08-25T12:00:00Z',
    updatedBy: 'System Baseline',
  },
  {
    countryCode: 'ARE',
    countryNameAr: 'الإمارات العربية المتحدة',
    countryNameEn: 'United Arab Emirates',
    standardDutyPercent: 5.0,
    newPersonalGoodsDutyPercent: 5.0,
    commercialNewDutyPercent: 8.0,
    usedPersonalExempt: true,
    minExemptValueUsd: 150.0,
    notesAr: 'الأمتعة المستعملة معفاة. البضائع الجديدة تخضع لنسبة جمركية موحدة 5%.',
    notesEn: 'Used effects exempt 0%. Standard 5% on new imports.',
    lastUpdated: '2026-08-25T12:00:00Z',
    updatedBy: 'System Baseline',
  },
  {
    countryCode: 'TUR',
    countryNameAr: 'الجمهورية التركية',
    countryNameEn: 'Turkey',
    standardDutyPercent: 18.0,
    newPersonalGoodsDutyPercent: 15.0,
    commercialNewDutyPercent: 20.0,
    usedPersonalExempt: true,
    minExemptValueUsd: 30.0,
    notesAr: 'الأمانات الشخصية المستعملة معفاة 0%. البضائع والملابس الجديدة 15%.',
    notesEn: 'Used items 0%. New goods 15-20%.',
    lastUpdated: '2026-08-25T12:00:00Z',
    updatedBy: 'System Baseline',
  },
];

const senderUser: User = {
  id: 'usr-sender-101',
  fullName: 'طارق الهاشمي (Tariq Al-Hashemi)',
  email: 'tariq.sender@thouesa.com',
  phone: '+962 79 123 4567',
  role: 'SENDER',
  kycStatus: 'VERIFIED',
  isActive: true,
  preferredLocale: 'ar',
  nationality: 'أردني (Jordanian)',
  nationalId: '9841029381',
  passportNumber: 'N98241288',
  idDocumentFrontUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
  idDocumentBackUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
  selfieWithIdUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  totalShipments: 14,
  createdAt: '2026-01-15T10:00:00Z',
};

const travelerUser: User = {
  id: 'usr-traveler-202',
  fullName: 'كريم بوجمعة (Karim Boujemaa)',
  email: 'karim.traveler@thouesa.com',
  phone: '+213 55 987 6543',
  role: 'TRAVELER',
  kycStatus: 'VERIFIED',
  isActive: true,
  preferredLocale: 'ar',
  nationality: 'جزائري (Algerian)',
  nationalId: '109841928341',
  passportNumber: 'DZ20268841',
  idDocumentFrontUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
  passportPhotoUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
  selfieWithIdUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
  avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  rating: 4.96,
  totalTrips: 28,
  createdAt: '2025-11-20T08:30:00Z',
};

const hubAgentUser: User = {
  id: 'usr-agent-303',
  fullName: 'عمر النجار (Omar Al-Najjar)',
  email: 'agent.amman@thouesa.com',
  phone: '+962 78 888 9911',
  role: 'HUB_AGENT',
  kycStatus: 'VERIFIED',
  isActive: true,
  preferredLocale: 'ar',
  avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  createdAt: '2025-08-01T09:00:00Z',
};

const hubManagerUser: User = {
  id: 'usr-manager-404',
  fullName: 'ياسين بلخير (Yassine Belkheir)',
  email: 'manager.algiers@thouesa.com',
  phone: '+213 21 73 00 22',
  role: 'HUB_MANAGER',
  kycStatus: 'VERIFIED',
  isActive: true,
  preferredLocale: 'ar',
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  createdAt: '2025-05-10T12:00:00Z',
};

const adminUser: User = {
  id: 'usr-admin-001',
  fullName: 'د. ضياء الحوت (Eng. Diya Al-Hout)',
  email: 'admin@thouesa.com',
  phone: '+962 79 000 1122',
  role: 'MASTER_ADMIN',
  kycStatus: 'VERIFIED',
  isActive: true,
  preferredLocale: 'ar',
  avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  createdAt: '2025-01-01T00:00:00Z',
};

export const DEMO_PROFILES: Record<string, User> = {
  sender: senderUser,
  traveler: travelerUser,
  hubAgent: hubAgentUser,
  hubManager: hubManagerUser,
  admin: adminUser,
  SENDER: senderUser,
  TRAVELER: travelerUser,
  HUB_AGENT: hubAgentUser,
  HUB_MANAGER: hubManagerUser,
  MASTER_ADMIN: adminUser,
};

export interface CustomerStatusConfig {
  labelAr: string;
  labelEn: string;
  badgeClass: string;
  dotColor: string;
  descriptionAr: string;
  descriptionEn: string;
}

export const CUSTOMER_SHIPMENT_STATUS_LABELS: Record<string, CustomerStatusConfig> = {
  DRAFT: {
    labelAr: 'مسودة',
    labelEn: 'Draft',
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-300',
    dotColor: 'bg-slate-400',
    descriptionAr: 'مسودة طلب غير مكتملة',
    descriptionEn: 'Incomplete order draft',
  },
  PENDING: {
    labelAr: 'قيد المراجعة',
    labelEn: 'Under Review',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    dotColor: 'bg-amber-400',
    descriptionAr: 'طلبك قيد المراجعة والتأكيد',
    descriptionEn: 'Order under review and confirmation',
  },
  PENDING_REVIEW: {
    labelAr: 'قيد المراجعة',
    labelEn: 'Under Review',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    dotColor: 'bg-amber-400',
    descriptionAr: 'طلبك قيد المراجعة والتأكيد',
    descriptionEn: 'Order under review and confirmation',
  },
  PENDING_DROPOFF: {
    labelAr: 'بانتظار تسليم الطرد للفرع',
    labelEn: 'Awaiting Hub Drop-off',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    dotColor: 'bg-amber-400',
    descriptionAr: 'يرجى تسليم الطرد إلى فرع ثويسة المعتمد',
    descriptionEn: 'Please drop off parcel at the designated hub',
  },
  PENDING_HUB_DROPOFF: {
    labelAr: 'بانتظار تسليم الطرد للفرع',
    labelEn: 'Awaiting Hub Drop-off',
    badgeClass: 'bg-amber-50 text-amber-700 border-amber-200',
    dotColor: 'bg-amber-400',
    descriptionAr: 'يرجى تسليم الطرد إلى فرع ثويسة المعتمد',
    descriptionEn: 'Please drop off parcel at the designated hub',
  },
  RECEIVED_AT_ORIGIN: {
    labelAr: 'تم استلام الطرد في فرع ثويسة',
    labelEn: 'Received at Origin Hub',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    dotColor: 'bg-blue-400',
    descriptionAr: 'تم استلام الطرد في فرع المنشأ وجاري التجهيز',
    descriptionEn: 'Parcel received at origin branch and being processed',
  },
  RECEIVED_AT_ORIGIN_HUB: {
    labelAr: 'تم استلام الطرد في فرع ثويسة',
    labelEn: 'Received at Origin Hub',
    badgeClass: 'bg-blue-50 text-blue-700 border-blue-200',
    dotColor: 'bg-blue-400',
    descriptionAr: 'تم استلام الطرد في فرع المنشأ وجاري التجهيز',
    descriptionEn: 'Parcel received at origin branch and being processed',
  },
  INSPECTED_SEALED: {
    labelAr: 'اكتمل فحص وتجهيز الطرد',
    labelEn: 'Inspected & Sealed',
    badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    dotColor: 'bg-indigo-400',
    descriptionAr: 'تم الفحص الأمني ووزن وتغليف وقفل الطرد',
    descriptionEn: 'Parcel security inspected, weighed and sealed',
  },
  INSPECTED_AND_SEALED: {
    labelAr: 'اكتمل فحص وتجهيز الطرد',
    labelEn: 'Inspected & Sealed',
    badgeClass: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    dotColor: 'bg-indigo-400',
    descriptionAr: 'تم الفحص الأمني ووزن وتغليف وقفل الطرد',
    descriptionEn: 'Parcel security inspected, weighed and sealed',
  },
  WEIGHT_ADJUSTMENT_PENDING: {
    labelAr: 'بانتظار موافقة فرق الوزن',
    labelEn: 'Weight Adjustment Pending',
    badgeClass: 'bg-orange-50 text-orange-700 border-orange-200',
    dotColor: 'bg-orange-400',
    descriptionAr: 'يوجد تعديل في الوزن الفعلي يتطلب موافقتك',
    descriptionEn: 'Actual weight difference requires your approval',
  },
  WEIGHT_DISCREPANCY_PENDING: {
    labelAr: 'بانتظار موافقة فرق الوزن',
    labelEn: 'Weight Adjustment Pending',
    badgeClass: 'bg-orange-50 text-orange-700 border-orange-200',
    dotColor: 'bg-orange-400',
    descriptionAr: 'يوجد تعديل في الوزن الفعلي يتطلب موافقتك',
    descriptionEn: 'Actual weight difference requires your approval',
  },
  ASSIGNED_TO_TRIP: {
    labelAr: 'تم تجهيز الطلب للنقل',
    labelEn: 'Prepared for Transit',
    badgeClass: 'bg-sky-50 text-sky-700 border-sky-200',
    dotColor: 'bg-sky-400',
    descriptionAr: 'تم ربط الطرد بجدول النقل المعتمد',
    descriptionEn: 'Parcel assigned to authorized dispatch schedule',
  },
  ASSIGNED_TO_TRAVELER: {
    labelAr: 'تم تجهيز الطلب للنقل',
    labelEn: 'Prepared for Transit',
    badgeClass: 'bg-sky-50 text-sky-700 border-sky-200',
    dotColor: 'bg-sky-400',
    descriptionAr: 'تم ربط الطرد بجدول النقل المعتمد',
    descriptionEn: 'Parcel assigned to authorized dispatch schedule',
  },
  IN_TRANSIT: {
    labelAr: 'طلبك في مرحلة النقل',
    labelEn: 'In Transit',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    dotColor: 'bg-emerald-500',
    descriptionAr: 'الشحنة في طريقها إلى بلد الوجهة',
    descriptionEn: 'Shipment is en route to destination country',
  },
  IN_TRANSIT_AIR: {
    labelAr: 'طلبك في مرحلة النقل',
    labelEn: 'In Transit',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    dotColor: 'bg-emerald-500',
    descriptionAr: 'الشحنة في طريقها إلى بلد الوجهة',
    descriptionEn: 'Shipment is en route to destination country',
  },
  IN_FLIGHT: {
    labelAr: 'طلبك في مرحلة النقل',
    labelEn: 'In Transit',
    badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    dotColor: 'bg-emerald-500',
    descriptionAr: 'الشحنة في طريقها إلى بلد الوجهة',
    descriptionEn: 'Shipment is en route to destination country',
  },
  CUSTOMS_CLEARANCE: {
    labelAr: 'التخليص الجمركي بمطار الوجهة',
    labelEn: 'Customs Clearance',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
    dotColor: 'bg-purple-400',
    descriptionAr: 'الشحنة تخضع للتخليص الجمركي بمطار الوجهة',
    descriptionEn: 'Undergoing destination customs clearance',
  },
  CUSTOMS_HELD: {
    labelAr: 'ملاحظة جمركية / تدقيق إضافي',
    labelEn: 'Customs Review',
    badgeClass: 'bg-purple-50 text-purple-700 border-purple-200',
    dotColor: 'bg-purple-400',
    descriptionAr: 'الشحنة تخضع للمراجعة الجمركية الإضافية',
    descriptionEn: 'Customs inspection in progress',
  },
  RECEIVED_AT_DEST: {
    labelAr: 'وصل الطلب إلى فرع الوجهة',
    labelEn: 'Received at Destination Hub',
    badgeClass: 'bg-teal-50 text-teal-700 border-teal-200',
    dotColor: 'bg-teal-400',
    descriptionAr: 'وصل الطرد إلى فرع ثويسة في مدينة الوصول',
    descriptionEn: 'Parcel arrived at destination hub',
  },
  RECEIVED_AT_DEST_HUB: {
    labelAr: 'وصل الطلب إلى فرع الوجهة',
    labelEn: 'Received at Destination Hub',
    badgeClass: 'bg-teal-50 text-teal-700 border-teal-200',
    dotColor: 'bg-teal-400',
    descriptionAr: 'وصل الطرد إلى فرع ثويسة في مدينة الوصول',
    descriptionEn: 'Parcel arrived at destination hub',
  },
  READY_FOR_PICKUP: {
    labelAr: 'طلبك جاهز للاستلام',
    labelEn: 'Ready for Pickup',
    badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-300 font-bold',
    dotColor: 'bg-emerald-500',
    descriptionAr: 'يمكنك الآن استلام طردك من الفرع',
    descriptionEn: 'Your parcel is ready for collection',
  },
  READY_FOR_DELIVERY: {
    labelAr: 'طلبك جاهز للاستلام / قيد التوصيل',
    labelEn: 'Ready for Delivery',
    badgeClass: 'bg-teal-50 text-teal-700 border-teal-200',
    dotColor: 'bg-teal-500',
    descriptionAr: 'الشحنة جاهزة للتسليم أو التوصيل المنزلي',
    descriptionEn: 'Shipment ready for handover or doorstep delivery',
  },
  OUT_FOR_DELIVERY: {
    labelAr: 'قيد التوصيل للمستلم',
    labelEn: 'Out for Delivery',
    badgeClass: 'bg-teal-50 text-teal-700 border-teal-200',
    dotColor: 'bg-teal-500',
    descriptionAr: 'مندوب التوصيل في طريقه لتسليم الطرد',
    descriptionEn: 'Courier is on the way to deliver the package',
  },
  DELIVERED: {
    labelAr: 'تم التسليم بنجاح',
    labelEn: 'Delivered',
    badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    dotColor: 'bg-emerald-600',
    descriptionAr: 'تم تسليم الشحنة بنجاح للمستلم',
    descriptionEn: 'Package delivered successfully to recipient',
  },
  COMPLETED: {
    labelAr: 'تم التسليم بنجاح',
    labelEn: 'Delivered',
    badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300',
    dotColor: 'bg-emerald-600',
    descriptionAr: 'تم تسليم الشحنة بنجاح للمستلم',
    descriptionEn: 'Package delivered successfully to recipient',
  },
  DISPUTED: {
    labelAr: 'طلب قيد النزاع / المتابعة',
    labelEn: 'Disputed / Under Review',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200',
    dotColor: 'bg-rose-500',
    descriptionAr: 'تم تسجيل نزاع وجاري المعالجة والتحقق',
    descriptionEn: 'Dispute opened and under resolution',
  },
  REJECTED_PROHIBITED: {
    labelAr: 'مرفوض - مواد غير مسموحة',
    labelEn: 'Rejected - Prohibited Goods',
    badgeClass: 'bg-red-50 text-red-700 border-red-200',
    dotColor: 'bg-red-500',
    descriptionAr: 'تم رفض الشحنة لاحتوائها على مواد محظورة',
    descriptionEn: 'Shipment rejected due to prohibited items',
  },
  CANCELLED: {
    labelAr: 'ملغي',
    labelEn: 'Cancelled',
    badgeClass: 'bg-slate-100 text-slate-600 border-slate-300',
    dotColor: 'bg-slate-400',
    descriptionAr: 'تم إلغاء الطلب',
    descriptionEn: 'Order was cancelled',
  },
};

export const getCustomerStatusInfo = (status?: string, isAr: boolean = true) => {
  const cfg = (status && CUSTOMER_SHIPMENT_STATUS_LABELS[status]) || {
    labelAr: status || 'قيد المعالجة',
    labelEn: status || 'Processing',
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-200',
    dotColor: 'bg-slate-400',
    descriptionAr: 'جاري متابعة حالة الطلب',
    descriptionEn: 'Tracking order status',
  };

  return {
    label: isAr ? cfg.labelAr : cfg.labelEn,
    description: isAr ? cfg.descriptionAr : cfg.descriptionEn,
    badgeClass: cfg.badgeClass,
    dotColor: cfg.dotColor,
  };
};

export const TRAVELER_TRIP_STATUS_LABELS: Record<
  string,
  {
    labelAr: string;
    labelEn: string;
    badgeClass: string;
    dotColor: string;
    descriptionAr?: string;
    descriptionEn?: string;
  }
> = {
  SUBMITTED: {
    labelAr: 'قيد المراجعة والتدقيق',
    labelEn: 'Under Review',
    badgeClass: 'bg-amber-50 text-amber-800 border-amber-200 font-medium',
    dotColor: 'bg-amber-500',
    descriptionAr: 'تم تسجيل الرحلة وبانتظار مراجعة وتدقيق بيانات التذكرة',
    descriptionEn: 'Trip registered and pending staff verification',
  },
  VERIFIED: {
    labelAr: 'معتمدة - بانتظار التأكيد',
    labelEn: 'Verified',
    badgeClass: 'bg-teal-50 text-teal-800 border-teal-200 font-bold',
    dotColor: 'bg-teal-500',
    descriptionAr: 'تم التحقق من تذكرة السفر واعتماد السعة المتاحة بنجاح',
    descriptionEn: 'Flight ticket and baggage capacity verified by THOUESA',
  },
  CONFIRMED: {
    labelAr: 'تم تأكيد السفر',
    labelEn: 'Trip Confirmed',
    badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-300 font-bold',
    dotColor: 'bg-emerald-500',
    descriptionAr: 'أكّد المسافر جاهزيته للسفر وقرب التوجه لفرع المغادرة',
    descriptionEn: 'Traveler confirmed readiness for dispatch',
  },
  PACKAGES_LINKED: {
    labelAr: 'تم إسناد الطرود للرحلة',
    labelEn: 'Packages Linked',
    badgeClass: 'bg-indigo-50 text-indigo-800 border-indigo-200 font-bold',
    dotColor: 'bg-indigo-500',
    descriptionAr: 'تم تخصيص الطرود المناسبة وتجهيز المانيفست في فرع المغادرة',
    descriptionEn: 'Parcels allocated to trip, manifest ready at origin hub',
  },
  DISPATCHED: {
    labelAr: 'بدأت عملية النقل (استلام العهدة)',
    labelEn: 'Dispatched / In Custody',
    badgeClass: 'bg-blue-50 text-blue-800 border-blue-200 font-bold',
    dotColor: 'bg-blue-500',
    descriptionAr: 'استلم المسافر الطرود والأختام من فرع المغادرة وبدأت العهدة',
    descriptionEn: 'Traveler received sealed custody from origin hub',
  },
  ARRIVED: {
    labelAr: 'تم تسجيل الوصول للبلد',
    labelEn: 'Arrived at Destination Country',
    badgeClass: 'bg-teal-50 text-teal-800 border-teal-200 font-bold',
    dotColor: 'bg-teal-500',
    descriptionAr: 'وصل المسافر إلى بلد الوجهة وبانتظار تسليم العهدة لفرع الوصول',
    descriptionEn: 'Arrived in destination country, pending hub handover',
  },
  COMPLETED: {
    labelAr: 'اكتملت العملية وتسليم العهدة',
    labelEn: 'Completed',
    badgeClass: 'bg-emerald-100 text-emerald-900 border-emerald-300 font-bold',
    dotColor: 'bg-emerald-600',
    descriptionAr: 'تم تسليم الطرود والأختام بنجاح لفرع الوجهة وإغلاق العهدة وتحرير الأرباح',
    descriptionEn: 'Custody delivered to destination hub and settled',
  },
  DELAYED: {
    labelAr: 'الرحلة متأخرة',
    labelEn: 'Flight Delayed',
    badgeClass: 'bg-orange-50 text-orange-800 border-orange-200 font-bold',
    dotColor: 'bg-orange-500',
    descriptionAr: 'تم الإبلاغ عن تأخير في موعد الرحلة مع بقاء الطرود مسندة',
    descriptionEn: 'Flight delayed, shipments kept on hold',
  },
  REJECTED: {
    labelAr: 'تعذر اعتماد الرحلة',
    labelEn: 'Rejected',
    badgeClass: 'bg-rose-50 text-rose-800 border-rose-200 font-bold',
    dotColor: 'bg-rose-500',
    descriptionAr: 'لم يتم اعتماد بيانات الرحلة لعدم تطابق الوثائق مع الشروط',
    descriptionEn: 'Trip verification declined due to invalid documents or rules',
  },
  CANCELLED: {
    labelAr: 'تم إلغاء الرحلة',
    labelEn: 'Cancelled',
    badgeClass: 'bg-slate-100 text-slate-600 border-slate-300',
    dotColor: 'bg-slate-400',
    descriptionAr: 'تم إلغاء الرحلة وفك حجز الضمان وإعادة توزيع الطرود',
    descriptionEn: 'Trip cancelled and parcels re-queued',
  },
  EMERGENCY_UNASSIGNED: {
    labelAr: 'إلغاء طارئ (إعادة للفرع)',
    labelEn: 'Emergency Unassigned',
    badgeClass: 'bg-purple-50 text-purple-800 border-purple-200 font-bold',
    dotColor: 'bg-purple-500',
    descriptionAr: 'تم فك إسناد الطرود طارئاً وإعادتها لطابور المطابقة بالفرع',
    descriptionEn: 'Parcels safely unassigned and returned to hub queue',
  },
  // Compatibility aliases
  SCHEDULED: {
    labelAr: 'قيد المراجعة والتدقيق',
    labelEn: 'Under Review',
    badgeClass: 'bg-amber-50 text-amber-800 border-amber-200',
    dotColor: 'bg-amber-500',
  },
  CHECKED_IN: {
    labelAr: 'تم تأكيد السفر',
    labelEn: 'Trip Confirmed',
    badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-300 font-bold',
    dotColor: 'bg-emerald-500',
  },
  IN_TRANSIT: {
    labelAr: 'بدأت عملية النقل (العهدة)',
    labelEn: 'In Transit',
    badgeClass: 'bg-blue-50 text-blue-800 border-blue-200 font-bold',
    dotColor: 'bg-blue-500',
  },
  IN_FLIGHT: {
    labelAr: 'بدأت عملية النقل (العهدة)',
    labelEn: 'In Flight',
    badgeClass: 'bg-blue-50 text-blue-800 border-blue-200 font-bold',
    dotColor: 'bg-blue-500',
  },
  ESCROW_LOCKED: {
    labelAr: 'الضمان المالي محجوز',
    labelEn: 'Deposit Secured',
    badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-300',
    dotColor: 'bg-emerald-500',
  },
  ESCROW_PAID: {
    labelAr: 'الضمان المالي محجوز',
    labelEn: 'Deposit Secured',
    badgeClass: 'bg-emerald-50 text-emerald-800 border-emerald-300',
    dotColor: 'bg-emerald-500',
  },
};

export const getTravelerTripStatusInfo = (status?: string, isAr: boolean = true) => {
  const cfg = (status && TRAVELER_TRIP_STATUS_LABELS[status]) || {
    labelAr: status || 'قيد المراجعة',
    labelEn: status || 'Under Review',
    badgeClass: 'bg-slate-100 text-slate-700 border-slate-200',
    dotColor: 'bg-slate-400',
    descriptionAr: 'جاري مراجعة الرحلة',
    descriptionEn: 'Reviewing trip details',
  };

  return {
    label: isAr ? cfg.labelAr : cfg.labelEn,
    description: isAr ? cfg.descriptionAr : cfg.descriptionEn,
    badgeClass: cfg.badgeClass,
    dotColor: cfg.dotColor,
  };
};
