import { ShippingRate, DailyExchangeRate, SettlementRecord, OperationalIncident, Currency } from '../types';

export const INITIAL_SHIPPING_RATES: ShippingRate[] = [
  // Chain 1: JO -> DZ (CUSTOMER_SHIPPING - SEND_PARCEL)
  {
    id: 'RATE-JO-DZ-CUST-v1',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    currency: 'JOD',
    ratePerKg: 4.5,
    minimumCharge: 5.0,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-06-01T00:00:00Z',
    effectiveUntil: '2026-08-31T23:59:59Z',
    version: 1,
    status: 'EXPIRED',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-06-01T08:00:00Z',
    reason: 'التعرفة التأسيسية لخدمة شحن الطرود الشخصية',
  },
  {
    id: 'RATE-JO-DZ-CUST-v2',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    currency: 'JOD',
    ratePerKg: 4.5,
    minimumCharge: 5.0,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-09-01T00:00:00Z',
    version: 2,
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-01T08:00:00Z',
    reason: 'تحديث التعرفة الربعية لخدمة الطرود الشخصية',
  },
  {
    id: 'RATE-JO-DZ-CUST-v3',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    currency: 'JOD',
    ratePerKg: 5.0,
    minimumCharge: 5.0,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-10-01T00:00:00Z',
    version: 3,
    status: 'SCHEDULED',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-02T10:00:00Z',
    reason: 'تعديل سنوي لرسوم الوقود ومناولة الترانزيت لمسار عمّان - الجزائر',
  },

  // Chain 2: JO -> DZ (TRAVELER_COMPENSATION - SEND_PARCEL)
  {
    id: 'RATE-JO-DZ-TRAV-v1',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    rateType: 'TRAVELER_COMPENSATION',
    pricingModel: 'PER_KG',
    currency: 'JOD',
    ratePerKg: 2.0,
    minimumCharge: 2.0,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-06-01T00:00:00Z',
    effectiveUntil: '2026-08-31T23:59:59Z',
    version: 1,
    status: 'EXPIRED',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-06-01T08:00:00Z',
    reason: 'التعرفة التأسيسية لتعويضات المسافرين',
  },
  {
    id: 'RATE-JO-DZ-TRAV-v2',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    rateType: 'TRAVELER_COMPENSATION',
    pricingModel: 'PER_KG',
    currency: 'JOD',
    ratePerKg: 2.0,
    minimumCharge: 2.0,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-09-01T00:00:00Z',
    version: 2,
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-01T08:00:00Z',
    reason: 'تثبيت عائد المسافر 2.00 دينار لكل كيلوغرام من الأردن للجزائر',
  },

  // Chain 3: DZ -> JO (CUSTOMER_SHIPPING - SEND_PARCEL)
  {
    id: 'RATE-DZ-JO-CUST-v1',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    currency: 'DZD',
    ratePerKg: 1500,
    minimumCharge: 1500,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-06-01T00:00:00Z',
    effectiveUntil: '2026-07-31T23:59:59Z',
    version: 1,
    status: 'EXPIRED',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-06-01T08:30:00Z',
    reason: 'التعرفة التأسيسية لشحن الطرود من الجزائر',
  },
  {
    id: 'RATE-DZ-JO-CUST-v2',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    currency: 'DZD',
    ratePerKg: 1650,
    minimumCharge: 1500,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-08-01T00:00:00Z',
    effectiveUntil: '2026-08-31T23:59:59Z',
    version: 2,
    status: 'EXPIRED',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-08-01T08:30:00Z',
    reason: 'تحديث تعرفة الطرود الشخصية تماشياً مع كلف التغليف والتأمين الميداني',
  },
  {
    id: 'RATE-DZ-JO-CUST-v3',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    currency: 'DZD',
    ratePerKg: 1800,
    minimumCharge: 1500,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-09-01T00:00:00Z',
    version: 3,
    status: 'ACTIVE',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-09-01T08:30:00Z',
    reason: 'تحديث تسعير الشحن من فروع الجزائر لعمّان',
  },

  // Chain 4: DZ -> JO (TRAVELER_COMPENSATION - SEND_PARCEL)
  {
    id: 'RATE-DZ-JO-TRAV-v1',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    rateType: 'TRAVELER_COMPENSATION',
    pricingModel: 'PER_KG',
    currency: 'DZD',
    ratePerKg: 1000,
    minimumCharge: 1000,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-06-01T00:00:00Z',
    effectiveUntil: '2026-08-31T23:59:59Z',
    version: 1,
    status: 'EXPIRED',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-06-01T08:30:00Z',
    reason: 'التعرفة التأسيسية لتعويضات المسافرين من الجزائر',
  },
  {
    id: 'RATE-DZ-JO-TRAV-v2',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    rateType: 'TRAVELER_COMPENSATION',
    pricingModel: 'PER_KG',
    currency: 'DZD',
    ratePerKg: 1200,
    minimumCharge: 1200,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-09-01T00:00:00Z',
    version: 2,
    status: 'ACTIVE',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-09-01T08:30:00Z',
    reason: 'تعويض المسافرين للرحلات المغادرة من الجزائر إلى الأردن',
  },
];

export const INITIAL_DAILY_EXCHANGE_RATES: DailyExchangeRate[] = [
  // Pair 1: JOD / DZD
  {
    id: 'FX-JOD-DZD-v1',
    baseCurrency: 'JOD',
    quoteCurrency: 'DZD',
    buyRate: 193.5, // 1 JOD = 193.50 DZD (THOUESA buys JOD)
    sellRate: 195.0, // 1 JOD = 195.00 DZD (THOUESA sells JOD)
    effectiveFrom: '2026-08-15T08:00:00Z',
    effectiveUntil: '2026-08-31T23:59:59Z',
    countryScope: 'GLOBAL',
    source: 'Treasury / Central Operations Desk',
    version: 1,
    status: 'EXPIRED',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-08-15T08:00:00Z',
    notes: 'سعر الصرف المعتمد لشهر آب (شراء: 193.50 | بيع: 195.00)',
  },
  {
    id: 'FX-JOD-DZD-v2',
    baseCurrency: 'JOD',
    quoteCurrency: 'DZD',
    buyRate: 193.5, // 1 JOD = 193.50 DZD (THOUESA buys JOD from traveler payout perspective)
    sellRate: 195.0, // 1 JOD = 195.00 DZD (THOUESA sells JOD)
    effectiveFrom: '2026-09-01T08:00:00Z',
    countryScope: 'GLOBAL',
    source: 'Treasury / Central Operations Desk',
    version: 2,
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-01T08:00:00Z',
    notes: 'السعر المعتمد لزوج الدينار الأردني والدينار الجزائري (شراء: 193.50 | بيع: 195.00)',
  },

  // Pair 2: DZD / JOD
  {
    id: 'FX-20260903-DZD-JOD',
    baseCurrency: 'DZD',
    quoteCurrency: 'JOD',
    buyRate: 0.00515, // 1 DZD = 0.00515 JOD (THOUESA buys DZD)
    sellRate: 0.00538, // 1 DZD = 0.00538 JOD (THOUESA sells DZD)
    effectiveFrom: '2026-09-03T07:00:00Z',
    countryScope: 'GLOBAL',
    source: 'Treasury / Central Operations Desk',
    version: 1,
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-03T07:00:00Z',
    notes: 'السعر الصباحي المعتمد لتسويات الطرود والمسافرين بين الأردن والجزائر',
  },

  // Pair 3: USD / JOD
  {
    id: 'FX-20260903-USD-JOD',
    baseCurrency: 'USD',
    quoteCurrency: 'JOD',
    buyRate: 0.708,
    sellRate: 0.71,
    effectiveFrom: '2026-09-03T07:00:00Z',
    countryScope: 'JO',
    source: 'Central Bank of Jordan Reference',
    version: 1,
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-03T07:00:00Z',
    notes: 'ربط رسمي مثبت للدينار الأردني مقابل الدولار',
  },

  // Pair 4: USD / DZD
  {
    id: 'FX-20260903-USD-DZD',
    baseCurrency: 'USD',
    quoteCurrency: 'DZD',
    buyRate: 133.5,
    sellRate: 135.2,
    effectiveFrom: '2026-09-03T07:00:00Z',
    countryScope: 'DZ',
    source: 'Bank of Algeria Interbank Fix',
    version: 1,
    status: 'ACTIVE',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-09-03T07:00:00Z',
    notes: 'سعر الصرف البنكي الرسمي في الجزائر',
  },
];

export const INITIAL_SETTLEMENTS: SettlementRecord[] = [
  {
    id: 'STL-C-00182',
    settlementNumber: 'STL-C-00182',
    type: 'CUSTOMER_PAYMENT',
    relatedUserId: 'CUST-JO-1042',
    relatedUserName: 'Mohammad Ahmad (محمد أحمد)',
    shipmentId: 'ship-182',
    trackingNumber: 'TH-0182',
    hubId: 'hub-amm',
    hubCode: 'AMM-HUB',
    route: 'JO → DZ',
    serviceType: 'SEND_PARCEL',

    // Pricing Snapshot (LOCKED)
    shippingRateId: 'RATE-JO-DZ-CUST-v2',
    shippingRateVersion: 'V2',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    appliedShippingRate: 4.50,
    billingWeightKg: 3.20,
    baseAmount: 14.40,
    baseCurrency: 'JOD',

    // FX Conversion Snapshot (LOCKED)
    settlementCurrency: 'DZD',
    exchangeRateId: 'FX-JOD-DZD-v4',
    rateVersion: 'V4',
    exchangeRateVersion: 'V4',
    fxSide: 'SELL',
    appliedFxRate: 195.00,
    convertedAmount: 2808.00,
    amountDue: 2808.00,
    amountReceived: 2808.00,
    paymentMethod: 'CASH',

    fees: 0.0,
    adjustments: 0.0,
    finalAmount: 2808.00,
    status: 'PAID',
    idempotencyKey: 'IDEMP-PAY-TH-0182-20260902',
    processedBy: 'EMP-JO-004',
    processedByName: 'خالد مصطفى (أمين صندوق فرع عمّان)',
    processedAt: '2026-09-02T10:15:00Z',
    receiptNumber: 'RCP-AMM-2026-0182',
    notes: 'تحصيل نقدي بالدينار الجزائري في كاونتر فرع عمّان للشحنة TH-0182',
  },
  {
    id: 'STL-T-00142',
    settlementNumber: 'STL-T-00142',
    type: 'TRAVELER_PAYOUT',
    relatedUserId: 'TRAV-DZ-991',
    relatedUserName: 'Ahmed Benali (أحمد بن علي)',
    tripId: 'TRIP-0142',
    flightNumber: 'RJ517',
    manifestId: 'MF-0142',
    hubId: 'hub-alg',
    hubCode: 'ALG-HUB',
    route: 'JO → DZ',

    // Traveler Compensation Snapshot (LOCKED)
    travelerCompensationRateId: 'RATE-JO-DZ-TRAV-v2',
    travelerCompensationRateVersion: 'V2',
    rateType: 'TRAVELER_COMPENSATION',
    pricingModel: 'PER_KG',
    appliedTravelerRate: 2.00,
    transportedWeightKg: 12.00,

    // Base Earnings
    baseAmount: 24.00,
    baseCurrency: 'JOD',

    // FX Conversion Snapshot (LOCKED)
    settlementCurrency: 'DZD',
    exchangeRateId: 'FX-JOD-DZD-v4',
    rateVersion: 'V4',
    exchangeRateVersion: 'V4',
    fxSide: 'BUY',
    appliedFxRate: 193.50,
    convertedAmount: 4644.00,
    paymentMethod: 'BANK_TRANSFER',

    fees: 0.0,
    adjustments: 0.0,
    finalAmount: 4644.00,
    status: 'SETTLED',
    idempotencyKey: 'IDEMP-PAYOUT-TRIP-0142-20260902',
    processedBy: 'EMP-DZ-002',
    processedByName: 'كريم بلقاسم (مدير فرع الجزائر)',
    processedAt: '2026-09-02T14:30:00Z',
    receiptNumber: 'RCP-ALG-PAYOUT-0142',
    notes: 'صرف مستحقات المسافر أحمد بن علي للرحلة TRIP-0142 بعد تفريغ وإغلاق المانيفست MF-0142 بنجاح',
  },
  {
    id: 'STL-2026-00891',
    settlementNumber: 'STL-2026-00891',
    type: 'CUSTOMER_PAYMENT',
    relatedUserId: 'CUST-JO-1042',
    relatedUserName: 'رامي ناصر',
    shipmentId: 'ship-101',
    trackingNumber: 'TH-AMM-ALG-202609-0112',
    hubId: 'hub-amm',
    hubCode: 'AMM-HUB',
    route: 'JO → DZ',
    serviceType: 'SEND_PARCEL',

    // Pricing Snapshot
    shippingRateId: 'RATE-JO-DZ-CUST-v1',
    shippingRateVersion: 'V1',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    appliedShippingRate: 6.00,
    billingWeightKg: 4.00,
    baseAmount: 24.0,
    baseCurrency: 'JOD',

    // FX Snapshot (Same Currency)
    settlementCurrency: 'JOD',
    fxSide: 'NONE',
    appliedFxRate: 1.0,
    convertedAmount: 24.0,
    amountDue: 24.0,
    amountReceived: 24.0,
    paymentMethod: 'CASH',

    fees: 0.0,
    adjustments: 0.0,
    finalAmount: 24.0,
    status: 'PAID',
    idempotencyKey: 'IDEMP-SETTL-00891-20260902',
    processedBy: 'EMP-JO-004',
    processedByName: 'خالد مصطفى (أمين صندوق)',
    processedAt: '2026-09-02T10:15:00Z',
    receiptNumber: 'RCP-AMM-2026-8812',
    notes: 'سداد نقدي عند تسليم الطرد في كاونتر فرع عمّان',
  },
  {
    id: 'STL-REF-00041',
    settlementNumber: 'STL-REF-00041',
    type: 'REFUND',
    relatedUserId: 'CUST-JO-1042',
    relatedUserName: 'سامي الدباس',
    shipmentId: 'ship-103',
    trackingNumber: 'TH-AMM-ALG-202609-0099',
    originalSettlementId: 'STL-2026-00880',
    hubId: 'hub-amm',
    hubCode: 'AMM-HUB',
    baseAmount: 18.0,
    baseCurrency: 'JOD',
    settlementCurrency: 'JOD',
    fxSide: 'NONE',
    appliedFxRate: 1.0,
    convertedAmount: 18.0,
    fees: 0.0,
    adjustments: 0.0,
    finalAmount: 18.0,
    status: 'SETTLED',
    refundReason: 'إلغاء الشحنة قبل المعالجة بناءً على طلب العميل واسترداد الرسوم كاملة',
    idempotencyKey: 'IDEMP-REFUND-00041-20260902',
    processedBy: 'EMP-JO-001',
    processedByName: 'أحمد خليل (مدير الفرع)',
    processedAt: '2026-09-02T16:00:00Z',
    receiptNumber: 'RCP-AMM-REF-00041',
    notes: 'استرداد نقدي معتمد للشحنة الملغاة',
  },
];

export const INITIAL_INCIDENTS: OperationalIncident[] = [
  {
    id: 'INC-0142',
    incidentNumber: 'INC-0142',
    type: 'MISSING_PACKAGE',
    category: 'MISSING_PACKAGE',
    entityType: 'MANIFEST',
    referenceNumber: 'MF-0142',
    priority: 'HIGH',
    status: 'UNDER_REVIEW',
    isBlocking: true,
    hubId: 'hub-alg',
    hubName: 'فرع الجزائر المركزي',
    relatedManifestId: 'MF-0142',
    relatedShipmentId: 'ship-102',
    trackingNumber: 'TH-0182',
    description: 'Expected shipment TH-0182 was not received at destination hub.',
    evidencePhotos: [],
    assignedEmployeeId: 'EMP-DZ-002',
    assignedEmployeeName: 'Karim Belkacem',
    assignedRole: 'Hub Manager',
    resolutionNotes: 'بانتظار التحقيق مع المسافر واستدعاء محضر تسليم مانيفست المغادرة',
    createdAt: '2026-09-03T10:30:00Z',
    updatedAt: '2026-09-03T11:15:00Z',
  },
  {
    id: 'INC-2026-0001',
    incidentNumber: 'INC-2026-0001',
    type: 'WEIGHT_DIFFERENCE',
    category: 'WEIGHT_DIFFERENCE',
    entityType: 'SHIPMENT',
    referenceNumber: 'TH-AMM-ALG-202609-0114',
    priority: 'HIGH',
    status: 'ACTION_REQUIRED',
    isBlocking: true,
    hubId: 'hub-amm',
    hubName: 'فرع عمّان الرئيسي',
    relatedShipmentId: 'ship-102',
    trackingNumber: 'TH-AMM-ALG-202609-0114',
    description: 'فارق وزن بين تصريح العميل (2.0 كغم) والوزن الفعلي للميزان (3.4 كغم). تم إيقاف الطرد وإرسال إشعار فرق التكلفة للعميل للموافقة.',
    evidencePhotos: [],
    assignedEmployeeId: 'EMP-JO-003',
    assignedEmployeeName: 'عمر التميمي',
    assignedRole: 'Lead Inspector',
    resolutionNotes: 'بانتظار سداد العميل لفارق الوزن عبر التطبيق',
    createdAt: '2026-09-02T11:20:00Z',
    updatedAt: '2026-09-02T11:25:00Z',
  },
  {
    id: 'INC-2026-0002',
    incidentNumber: 'INC-2026-0002',
    type: 'PROHIBITED_ITEM',
    category: 'PROHIBITED_ITEM',
    entityType: 'SHIPMENT',
    referenceNumber: 'TH-ALG-AMM-202609-0098',
    priority: 'HIGH',
    status: 'UNDER_REVIEW',
    isBlocking: true,
    hubId: 'hub-alg',
    hubName: 'فرع الجزائر المركزي',
    relatedShipmentId: 'ship-108',
    trackingNumber: 'TH-ALG-AMM-202609-0098',
    description: 'تم العثور على بطاريات ليثيوم غير مفصولة وشاحن توربيني غير معلن ضمن طرد إلكترونيات شخصي.',
    evidencePhotos: [],
    assignedEmployeeId: 'EMP-DZ-001',
    assignedEmployeeName: 'ياسين بن مهيدي',
    assignedRole: 'Security Officer',
    resolutionNotes: 'تم حجز المواد الممنوعة وإبلاغ المرسل بضرورة استلامها من الفرع',
    createdAt: '2026-09-02T09:10:00Z',
    updatedAt: '2026-09-02T09:45:00Z',
  },
  {
    id: 'INC-2026-0003',
    incidentNumber: 'INC-2026-0003',
    type: 'SEAL_MISMATCH',
    category: 'SEAL_MISMATCH',
    entityType: 'MANIFEST',
    referenceNumber: 'MF-ALG-AMM-001',
    priority: 'HIGH',
    status: 'OPEN',
    isBlocking: true,
    hubId: 'hub-amm',
    hubName: 'فرع عمّان الرئيسي',
    relatedShipmentId: 'ship-105',
    trackingNumber: 'TH-ALG-AMM-202609-0042',
    relatedManifestId: 'MF-ALG-AMM-001',
    description: 'رقم الختم الأمني على الطرد المستلم لا يطابق رقم الختم المسجل في مانيفست الوصول.',
    evidencePhotos: [],
    assignedEmployeeId: 'EMP-JO-001',
    assignedEmployeeName: 'أحمد خليل',
    assignedRole: 'Hub Manager',
    resolutionNotes: 'فتح تحقيق واستدعاء المانيفست الأصلي وصور الختم عند المغادرة',
    createdAt: '2026-09-02T15:40:00Z',
    updatedAt: '2026-09-02T15:40:00Z',
  },
];

export const INITIAL_RATE_HISTORY: any[] = [
  {
    id: 'RH-2026-001',
    rateId: 'RATE-JO-DZ-CUST-01',
    routeAr: 'الأردن ← الجزائر',
    routeEn: 'Jordan → Algeria',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    pricingModel: 'PER_KG',
    oldRateText: '7.00 JOD / KG',
    newRateText: '7.50 JOD / KG',
    changedBy: 'EMP-JO-014',
    changedByName: 'أحمد خليل (مدير الفرع)',
    date: '2026-09-03',
    versionText: 'v2 → v3',
    reason: 'تعديل سنوي لرسوم الوقود ومناولة الترانزيت لمسار عمّان - الجزائر',
  },
  {
    id: 'RH-2026-002',
    rateId: 'RATE-DZ-JO-CUST-01',
    routeAr: 'الجزائر ← الأردن',
    routeEn: 'Algeria → Jordan',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    pricingModel: 'PER_KG',
    oldRateText: '1,650 DZD / KG',
    newRateText: '1,800 DZD / KG',
    changedBy: 'EMP-DZ-002',
    changedByName: 'كريم بلقاسم (مدير فرع الجزائر)',
    date: '2026-09-01',
    versionText: 'v3 → v4',
    reason: 'تحديث تعرفة الطرود الشخصية تماشياً مع كلف التغليف والتأمين الميداني',
  },
  {
    id: 'RH-2026-003',
    rateId: 'RATE-JO-DZ-TRAV-01',
    routeAr: 'الأردن ← الجزائر',
    routeEn: 'Jordan → Algeria',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    pricingModel: 'PER_KG',
    oldRateText: '4.50 JOD / KG',
    newRateText: '5.00 JOD / KG',
    changedBy: 'EMP-JO-014',
    changedByName: 'أحمد خليل (مدير الفرع)',
    date: '2026-08-15',
    versionText: 'v1 → v2',
    reason: 'رفع نسبة مكافأة المسافر المعتمد لتحفيز قبول أوزان إضافية',
  },
];

export const INITIAL_EXCHANGE_RATES = INITIAL_DAILY_EXCHANGE_RATES;
