import { ShippingRate, DailyExchangeRate, SettlementRecord, OperationalIncident, Currency } from '../types';

export const INITIAL_SHIPPING_RATES: ShippingRate[] = [
  {
    id: 'RATE-JO-DZ-CUST-01',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    currency: 'JOD',
    ratePerKg: 7.5,
    minimumCharge: 5.0,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-09-01T00:00:00Z',
    version: 3,
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-01T08:00:00Z',
    reason: 'تحديث التعرفة الربعية لخدمة الطرود الشخصية',
  },
  {
    id: 'RATE-JO-DZ-TRAV-01',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    rateType: 'TRAVELER_COMPENSATION',
    pricingModel: 'PER_KG',
    currency: 'JOD',
    ratePerKg: 5.0,
    minimumCharge: 5.0,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-09-01T00:00:00Z',
    version: 2,
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-01T08:00:00Z',
    reason: 'تثبيت عائد المسافر لكل كيلوغرام من الأردن للجزائر',
  },
  {
    id: 'RATE-DZ-JO-CUST-01',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    rateType: 'CUSTOMER_SHIPPING',
    pricingModel: 'PER_KG',
    currency: 'DZD',
    ratePerKg: 1800,
    minimumCharge: 1500,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-09-01T00:00:00Z',
    version: 4,
    status: 'ACTIVE',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-09-01T08:30:00Z',
    reason: 'تحديث تسعير الشحن من فروع الجزائر لعمّان',
  },
  {
    id: 'RATE-DZ-JO-TRAV-01',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    rateType: 'TRAVELER_COMPENSATION',
    pricingModel: 'PER_KG',
    currency: 'DZD',
    ratePerKg: 1200,
    minimumCharge: 1200,
    minimumBillableWeightKg: 0.5,
    effectiveFrom: '2026-09-01T00:00:00Z',
    version: 2,
    status: 'ACTIVE',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-09-01T08:30:00Z',
    reason: 'تعويض المسافرين للرحلات المغادرة من الجزائر إلى الأردن',
  },
];

export const INITIAL_DAILY_EXCHANGE_RATES: DailyExchangeRate[] = [
  {
    id: 'FX-20260903-DZD-JOD',
    baseCurrency: 'DZD',
    quoteCurrency: 'JOD',
    buyRate: 0.00515, // 1 JOD = ~194 DZD
    sellRate: 0.00538, // 1 JOD = ~186 DZD
    effectiveFrom: '2026-09-03T07:00:00Z',
    countryScope: 'GLOBAL',
    source: 'Treasury / Central Operations Desk',
    version: 'FX-2026-09-03-01',
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-03T07:00:00Z',
    notes: 'السعر الصباحي المعتمد لتسويات الطرود والمسافرين بين الأردن والجزائر',
  },
  {
    id: 'FX-20260903-USD-JOD',
    baseCurrency: 'USD',
    quoteCurrency: 'JOD',
    buyRate: 0.708,
    sellRate: 0.71,
    effectiveFrom: '2026-09-03T07:00:00Z',
    countryScope: 'JO',
    source: 'Central Bank of Jordan Reference',
    version: 'FX-2026-09-03-01',
    status: 'ACTIVE',
    createdBy: 'EMP-JO-001 (Ahmad Khalil)',
    createdAt: '2026-09-03T07:00:00Z',
    notes: 'ربط رسمي مثبت للدينار الأردني مقابل الدولار',
  },
  {
    id: 'FX-20260903-USD-DZD',
    baseCurrency: 'USD',
    quoteCurrency: 'DZD',
    buyRate: 133.5,
    sellRate: 135.2,
    effectiveFrom: '2026-09-03T07:00:00Z',
    countryScope: 'DZ',
    source: 'Bank of Algeria Interbank Fix',
    version: 'FX-2026-09-03-01',
    status: 'ACTIVE',
    createdBy: 'EMP-DZ-002 (Karim Belkacem)',
    createdAt: '2026-09-03T07:00:00Z',
    notes: 'سعر الصرف البنكي الرسمي في الجزائر',
  },
];

export const INITIAL_SETTLEMENTS: SettlementRecord[] = [
  {
    id: 'STL-2026-00891',
    settlementNumber: 'STL-2026-00891',
    type: 'CUSTOMER_PAYMENT',
    relatedUserId: 'CUST-JO-1042',
    relatedUserName: 'رامي ناصر',
    shipmentId: 'ship-101',
    trackingNumber: 'TH-AMM-ALG-202609-0112',
    hubId: 'hub-amm',
    hubCode: 'AMM-HUB',
    baseAmount: 24.0,
    baseCurrency: 'JOD',
    settlementCurrency: 'JOD',
    fxSide: 'NONE',
    appliedFxRate: 1.0,
    convertedAmount: 24.0,
    fees: 0.0,
    adjustments: 0.0,
    finalAmount: 24.0,
    status: 'PAID',
    idempotencyKey: 'IDEMP-SETTL-00891-20260902',
    processedBy: 'EMP-JO-004',
    processedByName: 'خالد مصطفى',
    processedAt: '2026-09-02T10:15:00Z',
    receiptNumber: 'RCP-AMM-2026-8812',
    notes: 'سداد نقدي عند تسليم الطرد في كاونتر فرع عمّان',
  },
  {
    id: 'STL-2026-00892',
    settlementNumber: 'STL-2026-00892',
    type: 'TRAVELER_PAYOUT',
    relatedUserId: 'TRAV-DZ-991',
    relatedUserName: 'أحمد بن علي',
    tripId: 'trip-201',
    flightNumber: 'AH4012',
    manifestId: 'MF-ALG-AMM-001',
    hubId: 'hub-amm',
    hubCode: 'AMM-HUB',
    baseAmount: 12000.0,
    baseCurrency: 'DZD',
    settlementCurrency: 'JOD',
    exchangeRateId: 'FX-20260903-DZD-JOD',
    rateVersion: 'FX-2026-09-03-01',
    fxSide: 'SELL',
    appliedFxRate: 0.005263, // 1 JOD = 190 DZD
    convertedAmount: 63.16,
    fees: 0.0,
    adjustments: 0.0,
    finalAmount: 63.16,
    status: 'SETTLED',
    idempotencyKey: 'IDEMP-SETTL-00892-20260902',
    processedBy: 'EMP-JO-001',
    processedByName: 'أحمد خليل (مدير الفرع)',
    processedAt: '2026-09-02T14:30:00Z',
    receiptNumber: 'RCP-AMM-PAYOUT-991',
    notes: 'صرف أرباح نقل 10 كغم رحلة الجزائر - عمّان بالدينار الأردني بناءً على طلب المسافر',
  },
];

export const INITIAL_INCIDENTS: OperationalIncident[] = [
  {
    id: 'INC-2026-0001',
    incidentNumber: 'INC-2026-0001',
    category: 'WEIGHT_DIFFERENCE',
    priority: 'HIGH',
    status: 'ACTION_REQUIRED',
    hubId: 'hub-amm',
    hubName: 'فرع عمّان الرئيسي',
    relatedShipmentId: 'ship-102',
    trackingNumber: 'TH-AMM-ALG-202609-0114',
    description: 'فارق وزن بين تصريح العميل (2.0 كغم) والوزن الفعلي للميزان (3.4 كغم). تم إيقاف الطرد وإرسال إشعار فرق التكلفة للعميل للموافقة.',
    evidencePhotos: [],
    assignedEmployeeId: 'EMP-JO-003',
    assignedEmployeeName: 'عمر التميمي (مفتش معتمد)',
    resolutionNotes: 'بانتظار سداد العميل لفارق الوزن عبر التطبيق',
    createdAt: '2026-09-02T11:20:00Z',
    updatedAt: '2026-09-02T11:25:00Z',
  },
  {
    id: 'INC-2026-0002',
    incidentNumber: 'INC-2026-0002',
    category: 'PROHIBITED_ITEM',
    priority: 'HIGH',
    status: 'UNDER_REVIEW',
    hubId: 'hub-alg',
    hubName: 'فرع الجزائر المركزي',
    relatedShipmentId: 'ship-108',
    trackingNumber: 'TH-ALG-AMM-202609-0098',
    description: 'تم العثور على بطاريات ليثيوم غير مفصولة وشاحن توربيني غير معلن ضمن طرد إلكترونيات شخصي.',
    evidencePhotos: [],
    assignedEmployeeId: 'EMP-DZ-001',
    assignedEmployeeName: 'ياسين بن مهيدي (ضابط أمن وتفتيش)',
    resolutionNotes: 'تم حجز المواد الممنوعة وإبلاغ المرسل بضرورة استلامها من الفرع',
    createdAt: '2026-09-02T09:10:00Z',
    updatedAt: '2026-09-02T09:45:00Z',
  },
  {
    id: 'INC-2026-0003',
    incidentNumber: 'INC-2026-0003',
    category: 'SEAL_MISMATCH',
    priority: 'HIGH',
    status: 'OPEN',
    hubId: 'hub-amm',
    hubName: 'فرع عمّان الرئيسي',
    relatedShipmentId: 'ship-105',
    trackingNumber: 'TH-ALG-AMM-202609-0042',
    relatedManifestId: 'MF-ALG-AMM-001',
    description: 'رقم الختم الأمني على الطرد المستلم لا يطابق رقم الختم المسجل في مانيفست الوصول.',
    evidencePhotos: [],
    assignedEmployeeId: 'EMP-JO-001',
    assignedEmployeeName: 'أحمد خليل (مدير الفرع)',
    resolutionNotes: 'فتح تحقيق واستدعاء المانيفست الأصلي وصور الختم عند المغادرة',
    createdAt: '2026-09-02T15:40:00Z',
    updatedAt: '2026-09-02T15:40:00Z',
  },
];

export const INITIAL_RATE_HISTORY: any[] = [
  {
    id: 'RH-2026-001',
    rateId: 'RATE-JO-DZ-CUST-01',
    routeAr: 'الأردن ← الجزائر',
    routeEn: 'Jordan → Algeria',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    pricingModel: 'PER_KG',
    oldRateText: '7.00 JOD / KG',
    newRateText: '7.50 JOD / KG',
    changedBy: 'EMP-JO-014',
    changedByName: 'أحمد خليل (مدير الفرع)',
    date: '2026-09-03',
    versionText: 'v2 → v3',
    reason: 'تعديل سنوي لرسوم الوقود ومناولة الترانزيت لمسار عمّان - الجزائر',
  },
  {
    id: 'RH-2026-002',
    rateId: 'RATE-DZ-JO-CUST-01',
    routeAr: 'الجزائر ← الأردن',
    routeEn: 'Algeria → Jordan',
    originCountry: 'DZ',
    destinationCountry: 'JO',
    serviceType: 'SEND_PARCEL',
    pricingModel: 'PER_KG',
    oldRateText: '1,650 DZD / KG',
    newRateText: '1,800 DZD / KG',
    changedBy: 'EMP-DZ-002',
    changedByName: 'كريم بلقاسم (مدير فرع الجزائر)',
    date: '2026-09-01',
    versionText: 'v3 → v4',
    reason: 'تحديث تعرفة الطرود الشخصية تماشياً مع كلف التغليف والتأمين الميداني',
  },
  {
    id: 'RH-2026-003',
    rateId: 'RATE-JO-DZ-TRAV-01',
    routeAr: 'الأردن ← الجزائر',
    routeEn: 'Jordan → Algeria',
    originCountry: 'JO',
    destinationCountry: 'DZ',
    serviceType: 'SEND_PARCEL',
    pricingModel: 'PER_KG',
    oldRateText: '4.50 JOD / KG',
    newRateText: '5.00 JOD / KG',
    changedBy: 'EMP-JO-014',
    changedByName: 'أحمد خليل (مدير الفرع)',
    date: '2026-08-15',
    versionText: 'v1 → v2',
    reason: 'رفع نسبة مكافأة المسافر المعتمد لتحفيز قبول أوزان إضافية',
  },
];

export const INITIAL_EXCHANGE_RATES = INITIAL_DAILY_EXCHANGE_RATES;
